# Settings.yml
---
conf.py:
  project: Frontend Localization Guide
  copyright: 2000-2013
  version: 1.1.0
  release: 1.1.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization
    github_branch: latest
...
