# Settings.yml
---
conf.py:
  project: Frontend Localization Guide
  copyright: 2000-2013
  version: 1.1.0
  release: 1.1.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Guide-FrontendLocalization
    github_branch: latest
  latex_documents:
  - - Index
    - t3l10n.tex
    - Frontend Localization Guide
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
